# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Dtzi9TiDzT5sSNIKhMovh6G5NaJWr92
"""

import pandas as pd
import matplotlib.pyplot as plt

# load dataset
url = "https://raw.githubusercontent.com/mlco2/impact/master/data/instances.csv"
df = pd.read_csv(url)

df.head()

import pandas as pd

url = "https://raw.githubusercontent.com/mlco2/impact/master/data/instances.csv"
df = pd.read_csv(url)

print(df.columns)

pip install codecarbon

from codecarbon import EmissionsTracker
import tensorflow as tf
import numpy as np

tracker = EmissionsTracker(project_name="AI_Energy_Impact")
tracker.start()

model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

X = np.random.rand(1000, 20)
y = np.random.randint(0, 10, 1000)

model.fit(X, y, epochs=5, verbose=0)

tracker.stop()

import pandas as pd
import matplotlib.pyplot as plt

df_energy = pd.read_csv("codecarbon_output.csv")

plt.figure(figsize=(8,5))
plt.bar(['CPU', 'GPU'], [df_energy['cpu_energy_kWh'].sum(), df_energy['gpu_energy_kWh'].sum()], color=['blue', 'green'])
plt.ylabel("Total Energy (kWh)")
plt.title("Total Energy Consumption by CPU and GPU")
plt.show()

plt.figure(figsize=(6,4))
plt.bar(['Total CO2'], [df_energy['emissions_kg_CO2eq'].sum()], color='red')
plt.ylabel("CO2 Emissions (kg)")
plt.title("Estimated CO2 Emissions for ML Workload")
plt.show()

plt.figure(figsize=(8,5))
plt.plot(df_energy['timestamp'], df_energy['energy_consumed_kWh'], marker='o')
plt.xticks(rotation=45)
plt.ylabel("Energy Consumed (kWh)")
plt.title("Energy Consumption Over Time")
plt.tight_layout()
plt.show()

from codecarbon import EmissionsTracker
import tensorflow as tf
import numpy as np

tracker = EmissionsTracker(project_name="AI_Energy_Impact",
                           output_dir=".",
                           log_level="ERROR")

tracker.start()

model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

X = np.random.rand(1000, 20)
y = np.random.randint(0, 10, 1000)

model.fit(X, y, epochs=5, verbose=0)

tracker.stop()
print("CSV должен сохраниться в текущей папке с именем вида codecarbon_output_*.csv")

import os
os.listdir(".")

import pandas as pd
import matplotlib.pyplot as plt

df_energy = pd.read_csv("emissions.csv")

plt.figure(figsize=(8,5))
plt.bar(['CPU', 'GPU'], [df_energy['cpu_energy'].sum(), df_energy['gpu_energy'].sum()], color=['blue', 'green'])
plt.ylabel("Total Energy (kWh)")
plt.title("Total Energy Consumption by CPU and GPU")
plt.show()

plt.figure(figsize=(6,4))
plt.bar(['Total CO2'], [df_energy['emissions'].sum()], color='red')
plt.ylabel("CO2 Emissions (kg)")
plt.title("Estimated CO2 Emissions for ML Workload")
plt.show()

if 'timestamp' in df_energy.columns:
    plt.figure(figsize=(8,5))
    plt.plot(df_energy['timestamp'], df_energy['energy_consumed'], marker='o')

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("emissions.csv")

# Создадим столбец 'task' для разных нагрузок (например epochs)
df['task'] = ['Task 1', 'Task 2', 'Task 3', 'Task 4', 'Task 5'][:len(df)]

# Bar chart: Energy per task
plt.figure(figsize=(8,5))
plt.bar(df['task'], df['energy_consumed'], color='green')
plt.xlabel("ML Task")
plt.ylabel("Energy Consumed (kWh)")
plt.title("Energy Consumption per ML Task")
plt.show()

# Bar chart: CO2 per task
plt.figure(figsize=(8,5))
plt.bar(df['task'], df['emissions'], color='red')
plt.xlabel("ML Task")
plt.ylabel("CO2 Emissions (kg)")
plt.title("CO2 Emissions per ML Task")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("https://raw.githubusercontent.com/mlco2/impact/master/data/instances.csv")

print(df.head())

import pandas as pd
import matplotlib.pyplot as plt

# Загружаем датасет
df = pd.read_csv("https://raw.githubusercontent.com/mlco2/impact/master/data/instances.csv")

# Посмотрим первые строки
print(df.head())

# Проверяем пустые значения
print(df.isnull().sum())

# Удаляем строки с пустыми GPU или провайдерами
df_clean = df.dropna(subset=['gpu', 'provider'])

# Сколько осталось строк
print(f"Number of valid rows: {len(df_clean)}")

gpu_counts = df['gpu'].value_counts()

plt.figure(figsize=(8,5))
gpu_counts.plot(kind='bar', color='orange')
plt.xlabel("GPU Type")
plt.ylabel("Number of Instances")
plt.title("Frequency of GPU Types in Dataset")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

provider_counts = df['provider'].value_counts()

plt.figure(figsize=(6,4))
provider_counts.plot(kind='bar', color='green')
plt.xlabel("Cloud Provider")
plt.ylabel("Number of Instances")
plt.title("Number of Instances per Provider")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

import seaborn as sns

pivot = df.pivot_table(index='gpu', columns='provider', aggfunc='size', fill_value=0)

plt.figure(figsize=(8,6))
sns.heatmap(pivot, annot=True, fmt="d", cmap="YlGnBu")
plt.title("Number of GPU Instances per Provider")
plt.ylabel("GPU Type")
plt.xlabel("Provider")
plt.show()

# Импортируем библиотеки
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Загружаем исходный датасет
df = pd.read_csv("https://raw.githubusercontent.com/mlco2/impact/master/data/instances.csv")

# Проверяем данные
print(df.head())
print(df.isnull().sum())
df_clean = df.dropna(subset=['gpu', 'provider'])
print(f"Number of valid rows: {len(df_clean)}")

# -----------------------------
# Добавляем реальные TDP GPU (пример: W) для энергопотребления
gpu_tdp = {
    'Tesla V100': 250,
    'Tesla K80': 150,
    'A100': 300,
    'T4': 70,
    'P100': 250,
    'RTX 3090': 350,
    'RTX 4090': 450
}

# Добавляем колонку power_draw
df_clean['power_draw'] = df_clean['gpu'].map(gpu_tdp).fillna(200)  # неизвестные GPU = 200W

# -----------------------------
# 1️⃣ Частота использования GPU
gpu_counts = df_clean['gpu'].value_counts()
plt.figure(figsize=(8,5))
gpu_counts.plot(kind='bar', color='orange')
plt.xlabel("GPU Type")
plt.ylabel("Number of Instances")
plt.title("Frequency of GPU Types in Dataset")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# -----------------------------
# 2️⃣ Среднее энергопотребление GPU
gpu_energy = df_clean.groupby('gpu')['power_draw'].mean().sort_values(ascending=False)
plt.figure(figsize=(8,5))
gpu_energy.plot(kind='bar', color='red')
plt.xlabel("GPU Type")
plt.ylabel("Average Power Draw (W)")
plt.title("Average Energy Consumption by GPU")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# -----------------------------
# 3️⃣ Энергопотребление по провайдерам
provider_energy = df_clean.groupby('provider')['power_draw'].sum().sort_values(ascending=False)
plt.figure(figsize=(6,4))
provider_energy.plot(kind='bar', color='green')
plt.xlabel("Cloud Provider")
plt.ylabel("Total Power Draw (W)")
plt.title("Total Energy Consumption per Provider")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# -----------------------------
# 4️⃣ Heatmap: GPU vs Provider
pivot = df_clean.pivot_table(index='gpu', columns='provider', values='power_draw', aggfunc='sum', fill_value=0)
plt.figure(figsize=(10,6))
sns.heatmap(pivot, annot=True, fmt=".0f", cmap="YlGnBu")
plt.title("Total GPU Power Draw per Provider (W)")
plt.ylabel("GPU Type")
plt.xlabel("Provider")
plt.show()

# -----------------------------
# 5️⃣ Распределение мощности GPU
plt.figure(figsize=(8,5))
plt.hist(df_clean['power_draw'], bins=6, color='blue', edgecolor='black')
plt.xlabel("Power Draw (W)")
plt.ylabel("Number of Instances")
plt.title("Distribution of GPU Power Draw")
plt.show()

# -----------------------------
# 6️⃣ Расчет CO2 (пример)
# Используем коэффициент для AWS: 0.0004 tCO2/kWh
# Приведем W к kWh за 1 час
df_clean['co2_t'] = df_clean['power_draw'] * 1 / 1000 * 0.0004  # W*h → kWh → tCO2

plt.figure(figsize=(8,5))
plt.scatter(df_clean['gpu'], df_clean['co2_t'], color='purple', s=100)
plt.xlabel("GPU Type")
plt.ylabel("Estimated CO2 Emissions (t)")
plt.title("Estimated CO2 Emissions per GPU Instance")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
pl

# Импортируем библиотеки
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Загружаем исходный датасет
df = pd.read_csv("https://raw.githubusercontent.com/mlco2/impact/master/data/instances.csv")

# Проверяем данные
print(df.head())
print(df.isnull().sum())
df_clean = df.dropna(subset=['gpu', 'provider'])
print(f"Number of valid rows: {len(df_clean)}")

# -----------------------------
# Добавляем реальные TDP GPU (пример: W) для энергопотребления
gpu_tdp = {
    'Tesla V100': 250,
    'Tesla K80': 150,
    'A100': 300,
    'T4': 70,
    'P100': 250,
    'RTX 3090': 350,
    'RTX 4090': 450
}

# Добавляем колонку power_draw
df_clean['power_draw'] = df_clean['gpu'].map(gpu_tdp).fillna(200)  # неизвестные GPU = 200W

# -----------------------------
# 1️⃣ Частота использования GPU
gpu_counts = df_clean['gpu'].value_counts()
plt.figure(figsize=(8,5))
gpu_counts.plot(kind='bar', color='orange')
plt.xlabel("GPU Type")
plt.ylabel("Number of Instances")
plt.title("Frequency of GPU Types in Dataset")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# -----------------------------
# 2️⃣ Среднее энергопотребление GPU
gpu_energy = df_clean.groupby('gpu')['power_draw'].mean().sort_values(ascending=False)
plt.figure(figsize=(8,5))
gpu_energy.plot(kind='bar', color='red')
plt.xlabel("GPU Type")
plt.ylabel("Average Power Draw (W)")
plt.title("Average Energy Consumption by GPU")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# -----------------------------
# 3️⃣ Энергопотребление по провайдерам
provider_energy = df_clean.groupby('provider')['power_draw'].sum().sort_values(ascending=False)
plt.figure(figsize=(6,4))
provider_energy.plot(kind='bar', color='green')
plt.xlabel("Cloud Provider")
plt.ylabel("Total Power Draw (W)")
plt.title("Total Energy Consumption per Provider")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# -----------------------------
# 4️⃣ Heatmap: GPU vs Provider
pivot = df_clean.pivot_table(index='gpu', columns='provider', values='power_draw', aggfunc='sum', fill_value=0)
plt.figure(figsize=(10,6))
sns.heatmap(pivot, annot=True, fmt=".0f", cmap="YlGnBu")
plt.title("Total GPU Power Draw per Provider (W)")
plt.ylabel("GPU Type")
plt.xlabel("Provider")
plt.show()

# -----------------------------
# 5️⃣ Распределение мощности GPU
plt.figure(figsize=(8,5))
plt.hist(df_clean['power_draw'], bins=6, color='blue', edgecolor='black')
plt.xlabel("Power Draw (W)")
plt.ylabel("Number of Instances")
plt.title("Distribution of GPU Power Draw")
plt.show()

# -----------------------------
# 6️⃣ Расчет CO2 (пример)
# Используем коэффициент для AWS: 0.0004 tCO2/kWh
# Приведем W к kWh за 1 час
df_clean['co2_t'] = df_clean['power_draw'] * 1 / 1000 * 0.0004  # W*h → kWh → tCO2

plt.figure(figsize=(8,5))
plt.scatter(df_clean['gpu'], df_clean['co2_t'], color='purple', s=100)
plt.xlabel("GPU Type")
plt.ylabel("Estimated CO2 Emissions (t)")
plt.title("Estimated CO2 Emissions per GPU Instance")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()